spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/kevin
    username: root
    password: yuhjnm67GO!
  jpa:
    database: mysql
    generate-ddl: true
    hibernate:
      ddl-auto: update
