spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/kevin
    username: root
    password: 123456
  jpa:
    database: mysql
    generate-ddl: true
    hibernate:
      ddl-auto: update
