spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://${MYSQL_ADDRESS}/kevin
    username: ${MYSQL_USERNAME}
    password: ${MySQL_PASSWORD}
  jpa:
    database: mysql
    generate-ddl: true
    hibernate:
      ddl-auto: update
